BEGIN TRANSACTION;
INSERT INTO "inventory" VALUES (1,1,73,'2025-06-15');
INSERT INTO "inventory" VALUES (2,2,63,'2024-03-30');
INSERT INTO "inventory" VALUES (3,3,56,'2024-10-30');
INSERT INTO "inventory" VALUES (4,4,31,'2024-03-13');
INSERT INTO "inventory" VALUES (5,5,56,'2024-08-24');
INSERT INTO "inventory" VALUES (6,6,9,'2025-03-09');
INSERT INTO "inventory" VALUES (7,7,46,'2024-07-28');
INSERT INTO "inventory" VALUES (8,8,98,'2024-06-09');
INSERT INTO "inventory" VALUES (9,9,29,'2024-07-01');
INSERT INTO "inventory" VALUES (10,10,35,'2025-01-13');
INSERT INTO "medications" VALUES (1,'NutriSlim','A daily herbal supplement to support metabolism and reduce appetite. Contains green tea extract, fiber, and B-vitamins. Possible side effects: mild stomach upset or jitteriness if taken late in the day.');
INSERT INTO "medications" VALUES (2,'MetaboBoost','A thermogenic blend formulated with cayenne pepper and caffeine from green coffee beans. Helps increase calorie burn. Side effects may include elevated heart rate or restlessness.');
INSERT INTO "medications" VALUES (3,'ActiveFiber','A plant-based fiber supplement that promotes satiety and aids digestion. May help curb snacking between meals. Common side effects: bloating or mild gas.');
INSERT INTO "medications" VALUES (4,'DetoxCleanse','A gentle herbal detox featuring milk thistle and dandelion root to support natural liver function, paired with weight management. Can lead to more frequent urination or mild headaches initially.');
INSERT INTO "medications" VALUES (5,'ProteinBalance','A low-calorie protein shake designed to preserve lean muscle during weight loss. Suitable as a meal replacement. Some may experience stomach upset if lactose-intolerant.');
INSERT INTO "medications" VALUES (6,'OmegaTrim','A fish-oil–based formula that supports healthy lipid levels and metabolism. May reduce inflammation. Possible side effect: mild fishy aftertaste.');
INSERT INTO "medications" VALUES (7,'SlimGuard','An appetite suppressant featuring hoodia and glucomannan to control portion sizes and reduce cravings. Side effects include dry mouth or constipation.');
INSERT INTO "medications" VALUES (8,'LeanBCAA','Branch-chain amino acids that help maintain muscle mass during a calorie deficit. Taken pre- or post-workout. Generally well-tolerated; some may notice mild fatigue.');
INSERT INTO "medications" VALUES (9,'Enerburn','A pre-workout blend to boost energy expenditure, containing caffeine and green tea. Can enhance stamina. Excess use may cause jitteriness or rapid heartbeat.');
INSERT INTO "medications" VALUES (10,'CarbSmart','A carb-blocking supplement with white kidney bean extract to slow carbohydrate absorption. May help stabilize blood sugar levels. Mild digestive discomfort can occur.');
INSERT INTO "orders" VALUES (1,1,'pending',2);
INSERT INTO "orders" VALUES (2,2,'completed',5);
INSERT INTO "orders" VALUES (3,3,'pending',8);
INSERT INTO "orders" VALUES (4,4,'cancelled',11);
INSERT INTO "orders" VALUES (5,5,'pending',14);
INSERT INTO "orders" VALUES (6,6,'pending',17);
INSERT INTO "orders" VALUES (7,7,'completed',20);
INSERT INTO "orders" VALUES (8,8,'pending',23);
INSERT INTO "orders" VALUES (9,9,'pending',26);
INSERT INTO "orders" VALUES (10,10,'completed',29);
INSERT INTO "patients" VALUES (2,'Gwenette','Braybrooke','Type 2 diabetes diagnosed at 40, hypertension, and mild obesity. Recently started a low-carb diet and moderate exercise routine.',837291456);
INSERT INTO "patients" VALUES (5,'Arluene','Tregian','Asthma since childhood, seasonal allergies, and a history of migraines. Currently on an inhaler and antihistamines.',192847563);
INSERT INTO "patients" VALUES (8,'Lynsey','Bolles','Coronary artery disease, underwent bypass surgery at 55. On cholesterol-lowering medication and a heart-healthy diet.',475920318);
INSERT INTO "patients" VALUES (11,'Rafi','Yegorkov','Polycystic ovary syndrome (PCOS), irregular menstrual cycles, and mild acne. Following a hormone-regulating treatment plan.',623874905);
INSERT INTO "patients" VALUES (14,'Hadrian','Hallgalley','Chronic lower back pain due to a herniated disc, managed with physical therapy and occasional pain medication.',380612794);
INSERT INTO "patients" VALUES (17,'Trista','Dumini','Hypothyroidism diagnosed at 35, managed with levothyroxine. Reports occasional fatigue and weight gain.',519684207);
INSERT INTO "patients" VALUES (20,'Erica','Millsom','History of sports-related knee injuries, underwent ACL reconstruction surgery at 20. Currently in physical therapy.',746295130);
INSERT INTO "patients" VALUES (23,'Eolanda','Messager','Osteoporosis diagnosed at 60, history of fractures in the wrist and hip. On calcium and vitamin D supplements.',284076593);
INSERT INTO "patients" VALUES (26,'Gerry','Hallen','Diagnosed with generalized anxiety disorder at 35, managed with therapy and occasional medication.',961347802);
INSERT INTO "patients" VALUES (29,'Jessamyn','Costard','Rheumatoid arthritis diagnosed at 50, on immunosuppressive therapy. Reports occasional joint stiffness and pain.',508132479);
INSERT INTO "pharmacists" VALUES (3,'93554 Springview Park','asdfhog');
INSERT INTO "pharmacists" VALUES (6,'00024 Fordem Street','qL2~CSZ5RnfAD/@');
INSERT INTO "pharmacists" VALUES (9,'4517 Comanche Plaza','xT5tJxs"q?%<,rtM');
INSERT INTO "pharmacists" VALUES (12,'6952 Parkside Drive','hJ1|fQ%65=L%$');
INSERT INTO "pharmacists" VALUES (15,'173 Declaration Circle','qZ0"XCVxQ$');
INSERT INTO "pharmacists" VALUES (18,'502 Pierstorff Parkway','dJ4T0s.7Wx');
INSERT INTO "pharmacists" VALUES (21,'5 Delaware Place','sF3/("M~rU4d0L');
INSERT INTO "pharmacists" VALUES (24,'7918 Red Cloud Avenue','wS47,o/bPf');
INSERT INTO "pharmacists" VALUES (27,'23 Sherman Plaza','uM9xLlrqHt@');
INSERT INTO "pharmacists" VALUES (30,'23981 Kingsford Place','vJ68SdA{lG');
COMMIT;
