BEGIN TRANSACTION;
INSERT INTO "inventory" VALUES (1,1,73,'2025-06-15');
INSERT INTO "inventory" VALUES (2,2,63,'2024-03-30');
INSERT INTO "inventory" VALUES (3,3,56,'2024-10-30');
INSERT INTO "inventory" VALUES (4,4,31,'2024-03-13');
INSERT INTO "inventory" VALUES (5,5,56,'2024-08-24');
INSERT INTO "inventory" VALUES (6,6,9,'2025-03-09');
INSERT INTO "inventory" VALUES (7,7,46,'2024-07-28');
INSERT INTO "inventory" VALUES (8,8,98,'2024-06-09');
INSERT INTO "inventory" VALUES (9,9,29,'2024-07-01');
INSERT INTO "inventory" VALUES (10,10,35,'2025-01-13');
INSERT INTO "medications" VALUES (1,'NutriSlim','A daily herbal supplement to support metabolism and reduce appetite. Contains green tea extract, fiber, and B-vitamins. Possible side effects: mild stomach upset or jitteriness if taken late in the day.');
INSERT INTO "medications" VALUES (2,'MetaboBoost','A thermogenic blend formulated with cayenne pepper and caffeine from green coffee beans. Helps increase calorie burn. Side effects may include elevated heart rate or restlessness.');
INSERT INTO "medications" VALUES (3,'ActiveFiber','A plant-based fiber supplement that promotes satiety and aids digestion. May help curb snacking between meals. Common side effects: bloating or mild gas.');
INSERT INTO "medications" VALUES (4,'DetoxCleanse','A gentle herbal detox featuring milk thistle and dandelion root to support natural liver function, paired with weight management. Can lead to more frequent urination or mild headaches initially.');
INSERT INTO "medications" VALUES (5,'ProteinBalance','A low-calorie protein shake designed to preserve lean muscle during weight loss. Suitable as a meal replacement. Some may experience stomach upset if lactose-intolerant.');
INSERT INTO "medications" VALUES (6,'OmegaTrim','A fish-oil–based formula that supports healthy lipid levels and metabolism. May reduce inflammation. Possible side effect: mild fishy aftertaste.');
INSERT INTO "medications" VALUES (7,'SlimGuard','An appetite suppressant featuring hoodia and glucomannan to control portion sizes and reduce cravings. Side effects include dry mouth or constipation.');
INSERT INTO "medications" VALUES (8,'LeanBCAA','Branch-chain amino acids that help maintain muscle mass during a calorie deficit. Taken pre- or post-workout. Generally well-tolerated; some may notice mild fatigue.');
INSERT INTO "medications" VALUES (9,'Enerburn','A pre-workout blend to boost energy expenditure, containing caffeine and green tea. Can enhance stamina. Excess use may cause jitteriness or rapid heartbeat.');
INSERT INTO "medications" VALUES (10,'CarbSmart','A carb-blocking supplement with white kidney bean extract to slow carbohydrate absorption. May help stabilize blood sugar levels. Mild digestive discomfort can occur.');
INSERT INTO "pharmacists" VALUES (3,'93554 Springview Park','qY4ij5GH<13jN9Gh');
INSERT INTO "pharmacists" VALUES (6,'00024 Fordem Street','qL2~CSZ5RnfAD/@');
INSERT INTO "pharmacists" VALUES (9,'4517 Comanche Plaza','xT5tJxs"q?%<,rtM');
INSERT INTO "pharmacists" VALUES (12,'6952 Parkside Drive','hJ1|fQ%65=L%$');
INSERT INTO "pharmacists" VALUES (15,'173 Declaration Circle','qZ0"XCVxQ$');
INSERT INTO "pharmacists" VALUES (18,'502 Pierstorff Parkway','dJ4T0s.7Wx');
INSERT INTO "pharmacists" VALUES (21,'5 Delaware Place','sF3/("M~rU4d0L');
INSERT INTO "pharmacists" VALUES (24,'7918 Red Cloud Avenue','wS47,o/bPf');
INSERT INTO "pharmacists" VALUES (27,'23 Sherman Plaza','uM9xLlrqHt@');
INSERT INTO "pharmacists" VALUES (30,'23981 Kingsford Place','vJ68SdA{lG');
INSERT INTO "orders" VALUES (1, 1, 'pending', 101);
INSERT INTO "orders" VALUES (2, 2, 'completed', 102);
INSERT INTO "orders" VALUES (3, 3, 'pending', 103);
INSERT INTO "orders" VALUES (4, 4, 'cancelled', 104);
INSERT INTO "orders" VALUES (5, 5, 'shipped', 105);
INSERT INTO "orders" VALUES (6, 6, 'pending', 106);
INSERT INTO "orders" VALUES (7, 7, 'completed', 107);
INSERT INTO "orders" VALUES (8, 8, 'pending', 108);
INSERT INTO "orders" VALUES (9, 9, 'pending', 101);
INSERT INTO "orders" VALUES (10, 10, 'completed', 109);
COMMIT;
